apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-deployment
  labels:
    app: webpage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
      - name: webpage
        image: aa7e414fdc/web_server:web_site   # Replace with your actual image name
        ports:
        - containerPort: 80
          hostPort: 8080   # Map container port 80 to host port 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webpage-service
spec:
  type: NodePort
  selector:
    app: webpage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100